name: Announce release on discord
on:
  release:
    types: [published]

jobs:
  upload_asset:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        args: |
          "<@254790994594234370>"
          "<:favs:673138127434416139> **FastAsyncVoxelSniper ${{ github.event.release.tag_name }}**"
          "Click here for the changelog: https://github.com/IntellectualSites/fastasyncvoxelsniper/releases/tag/${{ github.event.release.tag_name }"
